### ISSUE TITLE
Suggestion: Create containerfile (and possibly setup ci/cd build to make the images)

### ISSUE THREAD

**Issue by Nitrousoxide** [k9withabone/podlet#10]
This seems like an ideal project to create the containerfile and images so the project can be deployed through podman itself.  It would also reduce the number platforms you would need to support since you could just focus on a multicarch container rather than native installs.

**Comment by k9withabone** [comment]
Sounds like a good idea! Releases are currently managed with [cargo-dist](https://github.com/axodotdev/cargo-dist) so supporting the current four platforms is pretty easy.
