### ISSUE TITLE
Check for existing systemd service with the same name when writing a file

### ISSUE THREAD

**Issue by Nitrousoxide** [k9withabone/podlet#14]
Currently creating a podman.container file in the quadlet watched folder will have it create its own podman.service file which will break podman.  I opened a ticket on the podman github, but you may want to change the default name to "podlet.container" or "default.container" so that it avoids this issue.  Right now it creates "podman.container" which causes this bug if you use the export funtion to deploy it to the quadlet watched folder without a defined container name.

https://github.com/containers/podman/issues/18275

**Comment by k9withabone** [comment]
The name of the `.container` file is taken from the name of the image, so it's really only a problem if you're attempting to use podman within podman. I'll add a check and throw an error if the image name (if not provided a name) or the given name matches an existing service.
