### ISSUE TITLE
FEAT: generate from running container

### ISSUE THREAD

**Issue by johnmmcgee** [k9withabone/podlet#23]
It would be nice if it were possible to generate a systemd file from an already running container.

**Comment by johnmmcgee** [comment]
To add to this, possibly have it format podman generate systemd into quadlet format.

**Comment by k9withabone** [comment]
Generating a quadlet file from a running container has been an idea in the back of my mind for a while. However, it's a low priority.

> have it format podman generate systemd into quadlet format

Unfortunately, `podman generate systemd` is being deprecated in favor of quadlet (see the [podman 4.7.0 release notes](https://github.com/containers/podman/releases/tag/v4.7.0)). Other options for implementing this that I can think of are running the `podman container inspect` command or using the podman REST API.

**Comment by johnmmcgee** [comment]
@k9withabone I actually found this to work pretty well, but it would be nice if we could get this built in, in some way:

`podlet -i podman $(podman container inspect jellyfin | jq -r '.[0].Config.CreateCommand[2:] | join(" ")')`

**Comment by k9withabone** [comment]
Sorry I linked the wrong issue that commit. Please ignore it.
