### ISSUE TITLE
Unknown attribute "userns_mode"

### ISSUE THREAD

**Issue by Igetin** [k9withabone/podlet#31]
I have the following line in my compose file’s service configuration:

```yaml
userns_mode: "keep-id"
```

When trying to convert the compose file, podlet outputs the following error:

```
Error: 
   0: File `compose-debugging.yaml` is not a valid compose file
   1: services.test: unknown attribute "userns_mode", extensions must start with 'x-' (see https://docs.docker.com/compose/compose-file/#extension) at line 3 column 5
```

This should be supported by Quadlet in container/Kube units, according to the [documentation](https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html#container-units-container).

- [userns_mode in the Docker Compose file version 3 reference](https://docs.docker.com/compose/compose-file/compose-file-v3/#userns_mode)
- [userns_mode in the Compose Specification](https://github.com/compose-spec/compose-spec/blob/master/spec.md#userns_mode)

**Comment by k9withabone** [comment]
This is a bug in [docker-compose-types](https://github.com/stephanbuys/docker-compose-types), I'll create an issue there.
