### ISSUE TITLE
compose: `Exec=` incorrectly quoted for string `command`s

### ISSUE THREAD

**Issue by hakong** [k9withabone/podlet#36]
Should this not be
```
Exec="command" "-a" "arg" "-b" "arg"
```
?

I just generated a .container file from a compose that had 
```
command: mosquitto -c /mosquitto-no-auth.conf
```

And the resulting .container file had:
```
Exec="mosquitto -c /mosquitto-no-auth.conf"
```

Which didn't work AFAICS.

**Comment by k9withabone** [comment]
You are correct, nice catch. Except I don't think every arg needs to be quoted, just when it contains whitespace.
