### ISSUE TITLE
bind mount for podman run quay.io/k9withabone/podlet compose

### ISSUE THREAD

**Issue by chrismaster** [k9withabone/podlet#65]
Is there a volume mount point for podlet docker image?
podman run **-v=myYMLfolder:imageVolume** quay.io/k9withabone/podlet compose docker-compose.yml
Would be an easy way to use podlet without installing the binary.

**Comment by k9withabone** [comment]
There isn't one specified in the [Containerfile](https://github.com/k9withabone/podlet/blob/c1a057f266c8de1728474133f8856bf46c06c87e/Containerfile), but it shouldn't be required? See the container usage section of the [readme](https://github.com/k9withabone/podlet/tree/main?tab=readme-ov-file#in-a-container), especially the command at the end of that section.

**Comment by chrismaster** [comment]
Sorry, seems I did not read the Readme... (but I did)
Thx ...

**Comment by k9withabone** [comment]
Sounds like you figured it out and resolved the issue, but feel free to reopen if not or have additional questions.
