### ISSUE TITLE
Convert docker-compose files into Kubernetes YAML or `.container` quadlet files

### ISSUE THREAD

**Issue by Lunarequest** [k9withabone/podlet#9]
it would be very useful it podlet could convert compose files to quadlet files!

**Comment by k9withabone** [comment]
I agree! However, maybe generating kubernetes pod yaml from a compose file would be a better fit? I guess it depends on if you want each container to be more separate with each having their own `.container` file or all together in a pod defined in a kubernetes yaml file with a `.kube` quadlet file for systemd integration.

**Comment by Lunarequest** [comment]
> I agree! However, maybe generating kubernetes pod yaml from a compose file would be a better fit? I guess it depends on if you want each container to be more separate with each having their own `.container` file or all together in a pod defined in a kubernetes yaml file with a `.kube` quadlet file for systemd integration.

the main use case for docker-compose is that kubernetes is can be overly "heavy" so to speak for a simple container deployment eg just a webserver and a db. However I see the other side where someone may want to "translate" the compose to a k3s+podman deployment so maybe a flag to switch between the 2 modes?

**Comment by k9withabone** [comment]
The other thing with podman pods is that all containers in a pod share a network and UID/GID namespace. From my understanding, the default network configuration for rootless podman is such that containers not in a pod can't communicate with each other unless they use the host's IP. So someone translating a docker-compose file into separate `.container` files won't necessarily have the same behavior that they are expecting. However, a `.network` file could also be created that all the containers join via the "Network=" option.
I think I'm going to try to get in touch with the [podman-compose](https://github.com/containers/podman-compose) people to see what they might recommend and see where they had trouble converting docker things into podman.

**Comment by k9withabone** [comment]
Also, I've only been using docker/podman for about a year and only with my own small home lab. I haven't tried using k3s or anything very complicated, so please correct me if I say something wrong.
